
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE ENTERO ID MAS MENOS PARDER PARIZQ PORS : EE : E MAS T\n        | E MENOS T \n        | TT : T POR F\n    | T DIVIDE F \n    | FF : PARIZQ E PARDER\n        | ID'
    
_lr_action_items = {'PARIZQ':([0,5,7,8,9,10,],[5,5,5,5,5,5,]),'ID':([0,5,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,6,12,13,14,15,16,],[0,-1,-4,-7,-9,-2,-3,-5,-6,-8,]),'MAS':([2,3,4,6,11,12,13,14,15,16,],[7,-4,-7,-9,7,-2,-3,-5,-6,-8,]),'MENOS':([2,3,4,6,11,12,13,14,15,16,],[8,-4,-7,-9,8,-2,-3,-5,-6,-8,]),'PARDER':([3,4,6,11,12,13,14,15,16,],[-4,-7,-9,16,-2,-3,-5,-6,-8,]),'POR':([3,4,6,12,13,14,15,16,],[9,-7,-9,9,9,-5,-6,-8,]),'DIVIDE':([3,4,6,12,13,14,15,16,],[10,-7,-9,10,10,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'E':([0,5,],[2,11,]),'T':([0,5,7,8,],[3,3,12,13,]),'F':([0,5,7,8,9,10,],[4,4,4,4,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_S','Parser.py',11),
  ('E -> E MAS T','E',3,'p_E','Parser.py',16),
  ('E -> E MENOS T','E',3,'p_E','Parser.py',17),
  ('E -> T','E',1,'p_E','Parser.py',18),
  ('T -> T POR F','T',3,'p_T','Parser.py',34),
  ('T -> T DIVIDE F','T',3,'p_T','Parser.py',35),
  ('T -> F','T',1,'p_T','Parser.py',36),
  ('F -> PARIZQ E PARDER','F',3,'p_F','Parser.py',53),
  ('F -> ID','F',1,'p_F','Parser.py',54),
]
